[build]
  command = "next build"
  commandOrigin = "config"
  publish = "/opt/build/repo/.next"
  publishOrigin = "config"
[[plugins]]
  inputs = "{}"
  origin = "ui"
  package = "netlify-plugin-nextjs"