backend:
  name: git-gateway
  repo: runacast/runacast.github.io
  branch: main
  base_url: "https://runacast.github.io"

site_url: https://rimaymanta.com

media_folder: "public/uploads"
public_folder: "/uploads"

scripts:
  - https://cdn.jsdelivr.net/npm/uuid@latest/dist/umd/uuidv4.min.js

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
collections:
  - label: "Blog in English"
    name: "english_posts"
    folder: "_posts"
    create: true
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - label: "Blog en Español"
    name: "spanish_posts"
    folder: "_posts"
    create: true
    filter: {field: "language", value: "es"}
    fields:
      - {label: "Lenguaje", name: "language", widget: "select", options: ["en", "es"]}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}