backend:
  name: git-gateway
  repo: runacast/runacast.github.io
  branch: main
  base_url: "https://runacast.github.io"

site_url: https://rimaymanta.com

media_folder: "public/uploads"
public_folder: "/uploads"

scripts:
  - https://cdn.jsdelivr.net/npm/uuid@latest/dist/umd/uuidv4.min.js

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
collections:
  - name: "pages"
    label: "Pages"
    widget: "object"
    label_singular: 'Post'
    folder: "src/pages"
    extension: "json"
    format: "json"
    slug: '{{slug}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Slug", name: "slug", widget: "string", hint: "post-title-one", default: 'post-title' }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          choose_url: true,
          required: false
        }
      - { label: "Body", name: "body", widget: "text" }
  - name: "posts"
    label: "Posts"
    widget: "object"
    label_singular: 'Post'
    folder: "src/posts"
    extension: "json"
    format: "json"
    slug: '{{slug}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Slug", name: "slug", widget: "string", hint: "post-title-one", default: 'post-title' }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          choose_url: true
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "",
          default: "YYYY-MM-DD HH:mm"
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["Tarjeta"] }
      - { label: "Body", name: "body", widget: "text", hint: "Contenido del post..." }